### ISSUE TITLE
Dates off from what is set to what is in Attributes

### ISSUE THREAD

**Issue by tetragram55** [pinkywafer/Anniversaries#106]
I love this add on, thank you for making it.
I noticed this today, I don't know when it started but it wasn't always like this.
I am using core-2021.6.4 with the latest version of Anniversaries 
The date set in the set up is as follows:
![HASS-Anniv-error-2](https://user-images.githubusercontent.com/26680748/122118141-8f8fd780-cddc-11eb-8d64-a397e25fff35.png)

But what is shown in Attributes is this:

![HASS-Anniv-error](https://user-images.githubusercontent.com/26680748/122118012-6a02ce00-cddc-11eb-8bda-5491d079af36.png)

**Comment by bbgott** [comment]
I'm having the same issue, but I am noticing it is only happening to newer entries.  Birthdays or anniversaries that I had in there from before are displaying the correct date.
I am running core-2021.6.5 and Anniversaries version 4.3.1

**Comment by pinkywafer** [comment]
Unable to reproduce.... Can you give any more info?

**Comment by Grey-Lancaster** [comment]
not sure what info you need. same issue.  Not sure when HA changed to the dropdown box to see the dates.  Did not notice it before.  Timezone America/Indiana/Indianapolis units imperial/Fahrenheit 

![image](https://user-images.githubusercontent.com/20055899/125797824-8c0b8641-d151-4597-8b90-9c77e4f44f66.png)
![image](https://user-images.githubusercontent.com/20055899/125798059-f58b066e-b385-428e-be92-22a76e3bc6bb.png)

**Comment by Grey-Lancaster** [comment]
perhaps having different sensor names?
![image](https://user-images.githubusercontent.com/20055899/125799238-33881433-9779-4f0a-b7a2-69cad7a46f3a.png)

**Comment by pinkywafer** [comment]
Sensor names shouldn't affect it.... But I'm wondering if timezone could be affecting it... The sensor is based on the date, so effectively the time in the datetime object is 0:00:00. I'm wondering if this is the issue... I'll investigate.

Also, just as a check..  can you tell me if the countdown number of days is reporting correctly, ie. It's not also a day off?

**Comment by Grey-Lancaster** [comment]
if I ask google how many days until it matched the # of days you display

**Comment by pinkywafer** [comment]
Thanks. I'll look into the date... Expect it's timezone related

**Comment by Grey-Lancaster** [comment]
The date should not be calculated in attributes ?  It should just pull/match from the input?

**Comment by Grey-Lancaster** [comment]
Or does it need to be calculated for the half anniversary?

**Comment by pinkywafer** [comment]
It's checked and converted to a datetime rather than a text (it could come from a template in the configuration.yaml) so it's most likely to be there.  Ie if the date returned to home assistant is 15/7/21@0:00:00UTC, that would equate to 14/7/21@20:00 Washington 

That's what I'm expecting anyway....  Leave it with me!

**Comment by pinkywafer** [comment]
well, so far, I'm drawing a blank.

If I add some extra debug lines would anyone who has this issue mind testing and send me back the logs please.

**Comment by pinkywafer** [comment]
OK, I've published a beta release with debug logging in an attempt to find out where this issue is coming from.
to install it using hacs, go to your integrations.  Find the Anniversaries integration.  Press the menu (Three dots).  Press Reinstall.
You should be presented with the option to select the version to install.  Turn on __show beta versions__.
Choose version 4.4.1b1

to enable the debug logging, you will need the following in your configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.anniversaries: debug
```
reboot home assistant and we should get some logging information

**Comment by Grey-Lancaster** [comment]
How long will it take for a debug file to show?  I have installed 1b1  added logger: and rebooted, but I do not see anything

**Comment by pinkywafer** [comment]
The log entries should appear as soon as you reboot (assuming you have anniversary sensors configured) or whenever you add a new one on the integrations page.  The logs should be in your main home assistant log. - on the log page you need to press load full home assistant log

**Comment by Grey-Lancaster** [comment]
I was looking in the aniverseries folder.  I misspelled test lol

anniversaries
Version: 4.4.1b1
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/pinkywafer/Anniversaries/issues
-------------------------------------------------------------------
2021-07-15 16:21:40 DEBUG (MainThread) [custom_components.anniversaries.sensor] teat - config string - 2020-07-17
2021-07-15 16:21:40 DEBUG (MainThread) [custom_components.anniversaries.sensor] teat - date - 2020-07-17 00:00:00
2021-07-15 16:21:40 DEBUG (MainThread) [custom_components.anniversaries.sensor] teat - formatted date - 2020-07-17
![image](https://user-images.githubusercontent.com/20055899/125853496-80a5a012-da3f-49c5-a7ca-10d64f9e1e06.png)

**Comment by pinkywafer** [comment]
Ok, so I believe that the issue started when Home assistant started using native types instead of attributes just being text.

In the example @tetragram55 gave at the beginning,  the date in attributes is now listed as: *December 21, 1960*
This (ignore that it's the wrong date for now) is a home assistant date formatted by home assistant. 
The date format option is configured as `%Y-%m-%d` which should give *1960-12-22*

So I have two options:
1. Keep the optional formatting and force the date attribute the be returned as a text
Or (and I think my preferred option)
2. Remove the configuration option for date format and let home assistant deal with the formatting and just ensure that the date is passed in a 'local' manner so that timezone issues do not give the wrong date

My reasoning for choosing 2...  No-one has raised any issues regarding the lack of formatting in the date attribute, so I'm assuming that it hasn't caused any issues. Also, using the native format should actually make any templating on this attribute easier. Additionally, of the date is formatted by home assistant, it then visually matches all other dates in home assistant.

**Comment by Grey-Lancaster** [comment]
well I really have no idea what you just said :)
All I want to do is when I expand attributes I want to see the actually date, not one off :)  Again could you just not show what the thing was set for without any calculation? The # of days is correct.
Thanks for working on it.
Grey

**Comment by bbgott** [comment]
I like the sound of option 2 because it will visually match other dates in home assistant

**Comment by Grey-Lancaster** [comment]
Any progress on this issue?  I do not want to miss my Birthday ;-)

**Comment by pinkywafer** [comment]
Can anyone please try the `timezone-fix-beta` release and let me know if that solves it? - For manual install, you only need the sensor.py from the [timezone-fix-test](https://github.com/pinkywafer/Anniversaries/tree/timezone-fix-test) branch.
To do hacs install, go to hacs and find the anniversaries integration.  Click the menu (3 dots).  Choose `Redownload`.  Ensure `Show beta versions` is turned on and choose the `timezone-fix-beta` release.  You'll need to reboot Home Assistant

**Comment by Grey-Lancaster** [comment]
![image](https://user-images.githubusercontent.com/20055899/148135177-e7e5bb0b-90a7-4ad5-904c-2facf6fdf3a5.png)
I did : To do hacs install, go to hacs and find the anniversaries integration. Click the menu (3 dots). Choose Redownload. Ensure Show beta versions is turned on and choose the 2022.01.04 release. You'll need to reboot Home Assistant

**Comment by pinkywafer** [comment]
Sorry my bad... I used an invalid version number.
I think I've fixed that now if you can redownload.

If not, revert to stable and I'll look again tomorrow

**Comment by Grey-Lancaster** [comment]
No it is all wrong.  It did not fix previous so I made a new entry for March 13th.  It still shows March 12th in attributes and the days (perhaps I should not have selected default, is off )
![image](https://user-images.githubusercontent.com/20055899/148136015-1590770c-e6f5-4c55-a41b-77776b9ca6cd.png)

**Comment by Grey-Lancaster** [comment]
Yes, I selected count up and I should have not checked anything

**Comment by pinkywafer** [comment]
So still just date that's off?

**Comment by Grey-Lancaster** [comment]
yes, 
![image](https://user-images.githubusercontent.com/20055899/148137583-b7f30fe7-ac5c-4094-9709-5591d2e71328.png)

**Comment by pinkywafer** [comment]
can you tell me if the sensor is updating at midnight (as it should) or at some other time?

**Comment by Grey-Lancaster** [comment]
Midnight

**Comment by pinkywafer** [comment]
Thanks - it looks like a frontend issue - I think I'm getting somewhere now!
seems unrelated to #110

**Comment by pinkywafer** [comment]
ok.  The date is correct (internally): the template: `{{state_attr("sensorname","date")}}` returns the correct date.
The problem is that the UI recognises the attribute as a date, assumes it's UTC and converts it in the UI only to the date to suit the browser settings
![bitmoji](https://sdk.bitmoji.com/render/panel/626dd453-b50e-4ee9-9dce-86d306043c85-d3fcfc4c-1981-4ec3-80ce-44af1aeefe45-v1.png?transparent=1&palette=1&width=246)
This is NOT what is intended.  I'll look into a way to stop this or a workaround.
In the meantime, anything else that reads the attribute should get the correct value!

**Comment by pinkywafer** [comment]
can you try the 2022.01.07 beta please?
I've forced the date into the "default" timezone.  Hopefully this will cure the issue, but we've lost the option to format the date - something that I think we'll just have to live with as this is how the UI now works

**Comment by Grey-Lancaster** [comment]
I also created a new one and it is the same, one day off

![image](https://user-images.githubusercontent.com/20055899/148591142-09be6b5e-0943-4340-8bb0-7687da83fbe0.png)

![image](https://user-images.githubusercontent.com/20055899/148591290-81c8a011-c0eb-41db-b747-210fde875d1c.png)

**Comment by pinkywafer** [comment]
Ok, let's try with the full datetime object - can you try 2022.01.07-2 please

**Comment by Grey-Lancaster** [comment]
dash 2 is not showing up for me yet

**Comment by pinkywafer** [comment]
on hacs, find anniversaries - press 3 dots - update information.
This saves you waiting for hacs to update!

**Comment by Grey-Lancaster** [comment]
well that is not working at all  dash 2
![image](https://user-images.githubusercontent.com/20055899/148596629-8248b8ae-9421-4d08-af4e-3982dcc67a84.png)

**Comment by pinkywafer** [comment]
OK - Home Assistant doesn't like dash in release numbers....
try 2022.01.07r2 instead!

**Comment by Grey-Lancaster** [comment]
working on it
figured I best do a full backup first :-)

**Comment by Grey-Lancaster** [comment]
sorry, no change on old entries or new ones
![image](https://user-images.githubusercontent.com/20055899/148599472-af9bc6f4-45ba-4da8-a178-8158608c9dc9.png)

**Comment by pinkywafer** [comment]
My bad... in my haste I released from the wrong branch!

can you try r3

**Comment by Grey-Lancaster** [comment]
That works, shows 12:00am 
YEA :-)
![image](https://user-images.githubusercontent.com/20055899/148601088-c44cee86-bda1-4ed4-b0cb-d255c9622aed.png)

**Comment by pinkywafer** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/ed5f5cd3-fabf-4854-b0b1-fa835f3df502-d3fcfc4c-1981-4ec3-80ce-44af1aeefe45-v1.png?transparent=1&palette=1&width=246)
Thanks for your help.
I've had enough for tonight!
I'll sort out removing the unneeded config options etc and updating docs then I'll make a new release.

**Comment by Grey-Lancaster** [comment]
I figured you must not be on my side of the pond.  Sleep well and thank you !

**Comment by pinkywafer** [comment]
closed by #114
