### ISSUE TITLE
Hassio 0.115b2 integration config error

### ISSUE THREAD

**Issue by bandric1** [pinkywafer/Anniversaries#74]
In 0.115b0 to b2 it is giving up a config error so they had changed something and broke aniversaries.

**Comment by pinkywafer** [comment]
This is affecting sensors configured in yaml mode from ha 0.115b.  i will investigate.
Config flow entries are still working fine

**Comment by pinkywafer** [comment]
Sorry, i had a typo in my config.yaml

Configured as in the reader examples, this is working fine on my 0.115b2 instance.

Please check you are running the latest version of anniversaries, or can you please give more details ie the message received at config error and how it is configured.

**Comment by bandric1** [comment]
Podrobnosti dnevnika (ERROR)
Logger: homeassistant.setup
Source: setup.py:138 
First occurred: 21:38:33 (1 occurrences) 
Last logged: 21:38:33

Setup failed for anniversaries: Requirements for anniversaries not found: ['uuid'].

**Comment by bandric1** [comment]
3.1.0 is latest right?

**Comment by pinkywafer** [comment]
This should have been resolved with version 3.1.0 of the component which was released a few days ago. Can you please check which version you have installed and update if necessary

**Comment by bandric1** [comment]
3.1.0 is my version and is still throwing uuid error.
115b2 hassio
Setup failed for anniversaries: Requirements for anniversaries not found: ['uuid'].

**Comment by pinkywafer** [comment]
Strange. It's working fine on my 0.115b2. Can you try to reinstall the component

**Comment by bandric1** [comment]
Ok its back online i guess it needed a reinstall.
